// Code generated by sqlc. DO NOT EDIT.
// source: air.sql

package db

import (
	"context"
)

const createAir = `-- name: CreateAir :one
INSERT INTO air (
  substanse_name,
  date_of_sampling,
  number_of_sample,
  concentration,
  unit_of_measure,
  location,
  longitude,
  latitude,
  license_area,
  num_of_license,
  company,
  method_of_determ,
  laboratory
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, substanse_name, date_of_sampling, number_of_sample, concentration, unit_of_measure, location, longitude, latitude, license_area, num_of_license, company, method_of_determ, laboratory, created_at
`

type CreateAirParams struct {
	SubstanseName  string  `json:"substanse_name"`
	DateOfSampling string  `json:"date_of_sampling"`
	NumberOfSample string  `json:"number_of_sample"`
	Concentration  float32 `json:"concentration"`
	UnitOfMeasure  string  `json:"unit_of_measure"`
	Location       string  `json:"location"`
	Longitude      string  `json:"longitude"`
	Latitude       string  `json:"latitude"`
	LicenseArea    string  `json:"license_area"`
	NumOfLicense   string  `json:"num_of_license"`
	Company        string  `json:"company"`
	MethodOfDeterm string  `json:"method_of_determ"`
	Laboratory     string  `json:"laboratory"`
}

func (q *Queries) CreateAir(ctx context.Context, arg CreateAirParams) (Air, error) {
	row := q.db.QueryRowContext(ctx, createAir,
		arg.SubstanseName,
		arg.DateOfSampling,
		arg.NumberOfSample,
		arg.Concentration,
		arg.UnitOfMeasure,
		arg.Location,
		arg.Longitude,
		arg.Latitude,
		arg.LicenseArea,
		arg.NumOfLicense,
		arg.Company,
		arg.MethodOfDeterm,
		arg.Laboratory,
	)
	var i Air
	err := row.Scan(
		&i.ID,
		&i.SubstanseName,
		&i.DateOfSampling,
		&i.NumberOfSample,
		&i.Concentration,
		&i.UnitOfMeasure,
		&i.Location,
		&i.Longitude,
		&i.Latitude,
		&i.LicenseArea,
		&i.NumOfLicense,
		&i.Company,
		&i.MethodOfDeterm,
		&i.Laboratory,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAir = `-- name: DeleteAir :exec
DELETE FROM air
WHERE id = $1
`

func (q *Queries) DeleteAir(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAir, id)
	return err
}

const getAir = `-- name: GetAir :one
SELECT id, substanse_name, date_of_sampling, number_of_sample, concentration, unit_of_measure, location, longitude, latitude, license_area, num_of_license, company, method_of_determ, laboratory, created_at FROM air
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAir(ctx context.Context, id int64) (Air, error) {
	row := q.db.QueryRowContext(ctx, getAir, id)
	var i Air
	err := row.Scan(
		&i.ID,
		&i.SubstanseName,
		&i.DateOfSampling,
		&i.NumberOfSample,
		&i.Concentration,
		&i.UnitOfMeasure,
		&i.Location,
		&i.Longitude,
		&i.Latitude,
		&i.LicenseArea,
		&i.NumOfLicense,
		&i.Company,
		&i.MethodOfDeterm,
		&i.Laboratory,
		&i.CreatedAt,
	)
	return i, err
}

const listAir = `-- name: ListAir :many
SELECT id, substanse_name, date_of_sampling, number_of_sample, concentration, unit_of_measure, location, longitude, latitude, license_area, num_of_license, company, method_of_determ, laboratory, created_at FROM air
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAirParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAir(ctx context.Context, arg ListAirParams) ([]Air, error) {
	rows, err := q.db.QueryContext(ctx, listAir, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Air{}
	for rows.Next() {
		var i Air
		if err := rows.Scan(
			&i.ID,
			&i.SubstanseName,
			&i.DateOfSampling,
			&i.NumberOfSample,
			&i.Concentration,
			&i.UnitOfMeasure,
			&i.Location,
			&i.Longitude,
			&i.Latitude,
			&i.LicenseArea,
			&i.NumOfLicense,
			&i.Company,
			&i.MethodOfDeterm,
			&i.Laboratory,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAir = `-- name: UpdateAir :exec
UPDATE air
SET substanse_name = $2
WHERE id = $1
`

type UpdateAirParams struct {
	ID            int64  `json:"id"`
	SubstanseName string `json:"substanse_name"`
}

func (q *Queries) UpdateAir(ctx context.Context, arg UpdateAirParams) error {
	_, err := q.db.ExecContext(ctx, updateAir, arg.ID, arg.SubstanseName)
	return err
}
