// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Air struct {
	ID             int64        `json:"id"`
	SubstanseName  string       `json:"substanse_name"`
	DateOfSampling string       `json:"date_of_sampling"`
	NumberOfSample string       `json:"number_of_sample"`
	Concentration  float32      `json:"concentration"`
	UnitOfMeasure  string       `json:"unit_of_measure"`
	Location       string       `json:"location"`
	Longitude      string       `json:"longitude"`
	Latitude       string       `json:"latitude"`
	LicenseArea    string       `json:"license_area"`
	NumOfLicense   string       `json:"num_of_license"`
	Company        string       `json:"company"`
	MethodOfDeterm string       `json:"method_of_determ"`
	Laboratory     string       `json:"laboratory"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type BottomSediment struct {
	ID              int64        `json:"id"`
	SubstanseName   string       `json:"substanse_name"`
	DateOfSampling  string       `json:"date_of_sampling"`
	NumberOfSample  string       `json:"number_of_sample"`
	TypeOfSediments string       `json:"type_of_sediments"`
	Concentration   float32      `json:"concentration"`
	UnitOfMeasure   string       `json:"unit_of_measure"`
	Location        string       `json:"location"`
	Longitude       string       `json:"longitude"`
	Latitude        string       `json:"latitude"`
	Reservoir       string       `json:"reservoir"`
	LicenseArea     string       `json:"license_area"`
	NumOfLicense    string       `json:"num_of_license"`
	Company         string       `json:"company"`
	MethodOfDeterm  string       `json:"method_of_determ"`
	Laboratory      string       `json:"laboratory"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type Snow struct {
	ID               int64        `json:"id"`
	SubstanseName    string       `json:"substanse_name"`
	DateOfSampling   string       `json:"date_of_sampling"`
	NumberOfSample   string       `json:"number_of_sample"`
	Concentration    float32      `json:"concentration"`
	UnitOfMeasure    string       `json:"unit_of_measure"`
	Location         string       `json:"location"`
	Longitude        string       `json:"longitude"`
	Latitude         string       `json:"latitude"`
	SourceOfEmission string       `json:"source_of_emission"`
	LicenseArea      string       `json:"license_area"`
	NumOfLicense     string       `json:"num_of_license"`
	Company          string       `json:"company"`
	MethodOfDeterm   string       `json:"method_of_determ"`
	Laboratory       string       `json:"laboratory"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

type Soil struct {
	ID             int64        `json:"id"`
	SubstanseName  string       `json:"substanse_name"`
	DateOfSampling string       `json:"date_of_sampling"`
	NumberOfSample string       `json:"number_of_sample"`
	SoilSubtype    string       `json:"soil_subtype"`
	Concentration  float32      `json:"concentration"`
	UnitOfMeasure  string       `json:"unit_of_measure"`
	Location       string       `json:"location"`
	Longitude      string       `json:"longitude"`
	Latitude       string       `json:"latitude"`
	LicenseArea    string       `json:"license_area"`
	NumOfLicense   string       `json:"num_of_license"`
	Company        string       `json:"company"`
	MethodOfDeterm string       `json:"method_of_determ"`
	Laboratory     string       `json:"laboratory"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type SurfaceWater struct {
	ID             int64        `json:"id"`
	SubstanseName  string       `json:"substanse_name"`
	DateOfSampling string       `json:"date_of_sampling"`
	NumberOfSample string       `json:"number_of_sample"`
	Concentration  float32      `json:"concentration"`
	UnitOfMeasure  string       `json:"unit_of_measure"`
	Location       string       `json:"location"`
	Longitude      string       `json:"longitude"`
	Latitude       string       `json:"latitude"`
	Reservoir      string       `json:"reservoir"`
	LicenseArea    string       `json:"license_area"`
	NumOfLicense   string       `json:"num_of_license"`
	Company        string       `json:"company"`
	MethodOfDeterm string       `json:"method_of_determ"`
	Laboratory     string       `json:"laboratory"`
	CreatedAt      sql.NullTime `json:"created_at"`
}
