// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateAir(ctx context.Context, arg CreateAirParams) (Air, error)
	CreateBottomSediments(ctx context.Context, arg CreateBottomSedimentsParams) (BottomSediment, error)
	CreateSnow(ctx context.Context, arg CreateSnowParams) (Snow, error)
	CreateSoil(ctx context.Context, arg CreateSoilParams) (Soil, error)
	CreateSurfaceWater(ctx context.Context, arg CreateSurfaceWaterParams) (SurfaceWater, error)
	DeleteAir(ctx context.Context, id int64) error
	DeleteBottomSediments(ctx context.Context, id int64) error
	DeleteSnow(ctx context.Context, id int64) error
	DeleteSoil(ctx context.Context, id int64) error
	DeleteSurfaceWater(ctx context.Context, id int64) error
	GetAir(ctx context.Context, id int64) (Air, error)
	GetBottomSediments(ctx context.Context, id int64) (BottomSediment, error)
	GetSnow(ctx context.Context, id int64) (Snow, error)
	GetSoil(ctx context.Context, id int64) (Soil, error)
	GetSurfaceWater(ctx context.Context, id int64) (SurfaceWater, error)
	ListAir(ctx context.Context, arg ListAirParams) ([]Air, error)
	ListBottomSediments(ctx context.Context, arg ListBottomSedimentsParams) ([]BottomSediment, error)
	ListSnow(ctx context.Context, arg ListSnowParams) ([]Snow, error)
	ListSoil(ctx context.Context, arg ListSoilParams) ([]Soil, error)
	ListSurfaceWater(ctx context.Context, arg ListSurfaceWaterParams) ([]SurfaceWater, error)
	UpdateAir(ctx context.Context, arg UpdateAirParams) error
	UpdateBottomSediments(ctx context.Context, arg UpdateBottomSedimentsParams) error
	UpdateSnow(ctx context.Context, arg UpdateSnowParams) error
	UpdateSoil(ctx context.Context, arg UpdateSoilParams) error
	UpdateSurfaceWater(ctx context.Context, arg UpdateSurfaceWaterParams) error
}

var _ Querier = (*Queries)(nil)
